# Generated by Django 2.2.7 on 2020-01-01 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Enter title here', max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('summary', models.CharField(default='You need to enter the summary', max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
